// ============================================================
// Service Configuration
// Add/edit your services to monitor here
// ============================================================

import { ServiceConfig, ServiceGroup } from "@/types";

const MBZUAI_BASE = "https://mbzuai-demo-app-nlkl2.ondigitalocean.app";
const LAWA_RAG_BASE = "https://lawa-rag-agent-xwbfu.ondigitalocean.app";
const AGENT_STUDIO_IP = "http://139.59.4.82";

// ─── Product Groups ──────────────────────────────────────────

export const serviceGroups: ServiceGroup[] = [
  {
    id: "mbzuai",
    name: "MBZUAI Chatbot",
    shortName: "MBZUAI",
    description: "MBZUAI University RAG Chatbot — Admissions, programs, research Q&A",
    icon: "GraduationCap",
    baseUrl: MBZUAI_BASE,
    repo: "github.com/riteshthawkar/lawa-mbzuai-demo",
    color: "violet",
  },
  {
    id: "lawa-rag",
    name: "LAWA RAG Agent",
    shortName: "LAWA RAG",
    description: "UAE Government Q&A Chatbot — Visas, laws, services, tourism",
    icon: "Landmark",
    baseUrl: LAWA_RAG_BASE,
    repo: "github.com/riteshthawkar/lawa-rag-app",
    color: "sky",
  },
  {
    id: "agent-studio",
    name: "LAWA Agent Studio",
    shortName: "Agent Studio",
    description: "AI Agent Building Platform — Website indexing, chatbot management, RAG pipeline (DigitalOcean Droplet)",
    icon: "BrainCircuit",
    baseUrl: AGENT_STUDIO_IP,
    repo: "github.com/riteshthawkar/lawa-agent-studio-unified",
    color: "rose",
  },
  {
    id: "external",
    name: "External APIs & LLM Providers",
    shortName: "External",
    description: "Third-party API dependencies — LLMs, vector databases, and more",
    icon: "Globe",
    baseUrl: "",
    color: "amber",
  },
];

export function getGroupById(id: string): ServiceGroup | undefined {
  return serviceGroups.find((g) => g.id === id);
}

// ─── Services ────────────────────────────────────────────────

export const servicesConfig: ServiceConfig[] = [
  // ═══════════════════════════════════════════════════════════
  // MBZUAI Demo — RAG Chatbot (DigitalOcean)
  // ═══════════════════════════════════════════════════════════

  {
    id: "mbzuai-health",
    name: "Health Check",
    description: "Deep health check: validates DB connection, Pinecone indexes, and embedding model",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-root",
    name: "Root Endpoint",
    description: "Basic liveness check — confirms the FastAPI server is responding",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-api-root",
    name: "API Root",
    description: "API gateway check — verifies /api prefix is routable",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "API is working",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "mbzuai-auth-login",
    name: "Auth Login",
    description: "Authentication endpoint availability (POST /api/auth/login)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/auth/login`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 422,
    method: "POST",
    enabled: true,
    tags: ["production", "auth"],
  },
  {
    id: "mbzuai-auth-me",
    name: "Auth /me",
    description: "Protected user profile endpoint (expects 401 without token)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/auth/me`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "auth"],
  },
  {
    id: "mbzuai-history-stats",
    name: "Analytics Stats",
    description: "Chat history statistics endpoint (/api/history/stats)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/history/stats`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-history-count",
    name: "Chat Count",
    description: "Total chat count endpoint (/api/history/count)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/history/count`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-metrics",
    name: "Prometheus Metrics",
    description: "Prometheus metrics export endpoint (/metrics)",
    category: "infrastructure",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/metrics`,
    checkType: "keyword",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedKeyword: "http_requests_total",
    method: "GET",
    enabled: true,
    tags: ["production", "monitoring"],
  },
  {
    id: "mbzuai-openapi",
    name: "OpenAPI Spec",
    description: "OpenAPI JSON specification availability (/openapi.json)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/openapi.json`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "mbzuai-docs",
    name: "Swagger Docs",
    description: "Interactive API documentation page (/docs)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "mbzuai-admin-pipeline",
    name: "Pipeline Settings",
    description: "Admin RAG pipeline settings (/api/admin/pipeline-settings). Expects 401 — auth guard active.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/admin/pipeline-settings`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "admin"],
  },
  {
    id: "mbzuai-topics",
    name: "Topics API",
    description: "Topic management endpoint (/api/topics)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/topics`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production"],
  },

  // ═══════════════════════════════════════════════════════════
  // LAWA RAG App — UAE Government Q&A Chatbot (DigitalOcean)
  // ═══════════════════════════════════════════════════════════

  {
    id: "lawa-rag-health",
    name: "Health Check",
    description: "Liveness check for the LAWA RAG FastAPI service (/health)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "lawa-rag-root",
    name: "Root Endpoint",
    description: "Basic server liveness — confirms FastAPI is up and responding",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "lawa-rag-api-root",
    name: "API Root",
    description: "API gateway routing check — verifies /api prefix is reachable",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/api`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "API is working",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "lawa-rag-telegram-chat",
    name: "Telegram Chat Endpoint",
    description: "HTTP chat endpoint for Telegram bot (POST /telegram-chat). Expects 422 without body.",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/telegram-chat`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 422,
    method: "POST",
    enabled: true,
    tags: ["production", "chat"],
  },
  {
    id: "lawa-rag-openapi",
    name: "OpenAPI Spec",
    description: "OpenAPI JSON specification availability (/openapi.json)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/openapi.json`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "lawa-rag-docs",
    name: "Swagger Docs",
    description: "Interactive Swagger API documentation page (/docs)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },

  // ═══════════════════════════════════════════════════════════
  // LAWA Agent Studio — AI Agent Building Platform (DO Droplet)
  // 3 services: Django Core (8000), Indexing (8080), Chatbot (8002)
  // Repo: github.com/riteshthawkar/lawa-agent-studio-unified
  // ═══════════════════════════════════════════════════════════

  // ─── Nginx Reverse Proxy ───────────────────────────────────
  {
    id: "studio-nginx",
    name: "Nginx Reverse Proxy",
    description: "Nginx gateway on port 80 — front door to the droplet",
    category: "infrastructure",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}/`,
    checkType: "http",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },

  // ─── Indexing Service (Port 8080) ──────────────────────────
  {
    id: "studio-indexing-health",
    name: "Indexing Service — Health",
    description: "FastAPI indexing service health check (:8080/health)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-root",
    name: "Indexing Service — Root",
    description: "Indexing API info endpoint (:8080/)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "running",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "studio-indexing-live",
    name: "Indexing Service — Liveness",
    description: "Kubernetes-style liveness probe (:8080/health/live)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/live`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "alive",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-detailed",
    name: "Indexing Service — Detailed Health",
    description: "Deep health: DB, Redis, Pinecone, Celery, Disk (:8080/health/detailed). Catches internal component failures.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-db",
    name: "Indexing Service — Database",
    description: "PostgreSQL connection from Indexing service (:8080/health/detailed → checks.database.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.database.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "studio-indexing-disk",
    name: "Indexing Service — Disk Space",
    description: "Disk usage on the Agent Studio droplet (:8080/health/detailed → checks.system.status)",
    category: "infrastructure",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.system.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "infrastructure"],
  },
  {
    id: "studio-indexing-stats",
    name: "Indexing Service — Stats",
    description: "Task statistics and service uptime (:8080/stats)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/stats`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "studio-indexing-docs",
    name: "Indexing Service — Swagger Docs",
    description: "Interactive API docs (:8080/docs)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },

  // ─── Chatbot Widget Service (Port 8002) ────────────────────
  {
    id: "studio-chatbot-health",
    name: "Chatbot Service — Health",
    description: "FastAPI chatbot widget service health (:8002/health)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-live",
    name: "Chatbot Service — Liveness",
    description: "Liveness probe — confirms chatbot service process is alive (:8002/health/live)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/live`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "alive",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-detailed",
    name: "Chatbot Service — Detailed Health",
    description: "Deep health: DB, Pinecone, LAWA integration (:8002/health/detailed). Catches internal component failures.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-db",
    name: "Chatbot Service — Database",
    description: "PostgreSQL connection from Chatbot service (:8002/health/detailed → checks.database.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.database.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "studio-chatbot-pinecone",
    name: "Chatbot Service — Pinecone",
    description: "Pinecone vector DB connection from Chatbot (:8002/health/detailed → checks.pinecone.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.pinecone.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "vector-db"],
  },
  {
    id: "studio-chatbot-lawa",
    name: "Chatbot Service — LAWA Integration",
    description: "LAWA platform integration health from Chatbot (:8002/health/detailed → checks.lawa_integration.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.lawa_integration.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },

  // ─── Django Core Backend (Port 8000) ───────────────────────
  {
    id: "studio-django-health",
    name: "Django Backend — Health",
    description: "Django core backend health check (:8000). Note: returns 400 if ALLOWED_HOSTS doesn't include the IP.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8000/health/`,
    checkType: "http",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 400, // Django rejects bare IP unless in ALLOWED_HOSTS — 400 = process is alive
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },

  // ═══════════════════════════════════════════════════════════
  // External APIs & LLM Providers
  // ═══════════════════════════════════════════════════════════

  {
    id: "openai-api",
    name: "OpenAI API",
    description: "OpenAI GPT API availability (used by MBZUAI + LAWA RAG for generation & reranking)",
    category: "external_api",
    group: "external",
    url: "https://api.openai.com/v1/models",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["external", "llm", "critical"],
  },
  {
    id: "anthropic-api",
    name: "Anthropic Claude API",
    description: "Anthropic Claude API availability",
    category: "external_api",
    group: "external",
    url: "https://api.anthropic.com/v1/messages",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "POST",
    enabled: true,
    tags: ["external", "llm"],
  },
  {
    id: "pinecone-api",
    name: "Pinecone API",
    description: "Pinecone vector database API (used by MBZUAI + LAWA RAG for hybrid retrieval)",
    category: "external_api",
    group: "external",
    url: "https://api.pinecone.io/",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["external", "vector-db", "critical"],
  },
];

export function getEnabledServices(): ServiceConfig[] {
  return servicesConfig.filter((s) => s.enabled);
}

export function getServiceById(id: string): ServiceConfig | undefined {
  return servicesConfig.find((s) => s.id === id);
}

export function getServicesByCategory(category: ServiceConfig["category"]): ServiceConfig[] {
  return servicesConfig.filter((s) => s.category === category && s.enabled);
}

export function getServicesByGroup(groupId: string): ServiceConfig[] {
  return servicesConfig.filter((s) => s.group === groupId && s.enabled);
}

export const categoryLabels: Record<ServiceConfig["category"], string> = {
  chatbot_backend: "Chatbot Backends",
  ai_agent_platform: "AI Agent Platforms",
  database: "Databases",
  external_api: "External APIs & LLM Providers",
  infrastructure: "Infrastructure",
  other: "Other Services",
};

export const categoryOrder: ServiceConfig["category"][] = [
  "chatbot_backend",
  "ai_agent_platform",
  "external_api",
  "database",
  "infrastructure",
  "other",
];
