// ============================================================
// Service Configuration
// Add/edit your services to monitor here
// ============================================================

import { ServiceConfig, ServiceGroup } from "@/types";

const MBZUAI_BASE = "https://mbzuai-demo-app-nlkl2.ondigitalocean.app";
const MBZUAI_UG_BASE = "https://mbzuai-undergraduate-program-euqch.ondigitalocean.app";
const LAWA_RAG_BASE = "https://lawa-rag-agent-xwbfu.ondigitalocean.app";
const AGENT_STUDIO_IP = "http://139.59.4.82";
const CHAT_PROBE_FAILURE_KEYWORDS = [
  "response generation failed",
  "please try again later",
  "unable to generate",
  "failed to generate",
  "deprecated model",
  "model_not_found",
  "no longer supported",
  "invalid model",
  "does not exist",
];
const CHAT_PROBE_HEADERS = {
  "content-type": "application/json",
  "x-health-probe": "true",
};

// ─── Product Groups ──────────────────────────────────────────

export const serviceGroups: ServiceGroup[] = [
  {
    id: "mbzuai",
    name: "MBZUAI Chatbot",
    shortName: "MBZUAI",
    description: "MBZUAI University RAG Chatbot — Admissions, programs, research Q&A",
    icon: "GraduationCap",
    baseUrl: MBZUAI_BASE,
    repo: "github.com/riteshthawkar/lawa-mbzuai-demo",
    color: "violet",
  },
  {
    id: "mbzuai-ug",
    name: "MBZUAI Undergraduate Chatbot",
    shortName: "MBZUAI UG",
    description: "MBZUAI Undergraduate Program RAG Chatbot — Program info, admissions, curriculum Q&A",
    icon: "GraduationCap",
    baseUrl: MBZUAI_UG_BASE,
    repo: "github.com/riteshthawkar/lawa-undergraduate-program-chatbot",
    color: "indigo",
  },
  {
    id: "lawa-rag",
    name: "LAWA RAG Agent",
    shortName: "LAWA RAG",
    description: "UAE Government Q&A Chatbot — Visas, laws, services, tourism",
    icon: "Landmark",
    baseUrl: LAWA_RAG_BASE,
    repo: "github.com/riteshthawkar/lawa-rag-app",
    color: "sky",
  },
  {
    id: "agent-studio",
    name: "LAWA Agent Studio",
    shortName: "Agent Studio",
    description: "AI Agent Building Platform — Website indexing, chatbot management, RAG pipeline (DigitalOcean Droplet)",
    icon: "BrainCircuit",
    baseUrl: AGENT_STUDIO_IP,
    repo: "github.com/riteshthawkar/lawa-agent-studio-unified",
    color: "rose",
  },
  {
    id: "external",
    name: "External APIs & LLM Providers",
    shortName: "External",
    description: "Third-party API dependencies — LLMs, vector databases, and more",
    icon: "Globe",
    baseUrl: "",
    color: "amber",
  },
];

export function getGroupById(id: string): ServiceGroup | undefined {
  return serviceGroups.find((g) => g.id === id);
}

// ─── Services ────────────────────────────────────────────────

export const servicesConfig: ServiceConfig[] = [
  // ═══════════════════════════════════════════════════════════
  // MBZUAI Demo — RAG Chatbot (DigitalOcean)
  // ═══════════════════════════════════════════════════════════

  {
    id: "mbzuai-health",
    name: "Health Check",
    description: "Deep health check: validates DB connection, Pinecone indexes, and embedding model",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-generation-health",
    name: "Generation Health",
    description: "Direct OpenAI generation probe (/health/generation). Catches deprecated or misconfigured LLM models.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health/generation`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    probeTier: "llm_generation",
    tokenCostEstimate: 220,
    enabled: true,
    tags: ["production", "critical", "llm"],
  },
  {
    id: "mbzuai-db",
    name: "Database Connection",
    description: "PostgreSQL connection from MBZUAI backend (/health → checks.database.status)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.database.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "mbzuai-pinecone",
    name: "Pinecone Connection",
    description: "Pinecone/vector-store readiness from MBZUAI (/health → checks.vector_store.status)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.vector_store.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "vector-db"],
  },
  {
    id: "mbzuai-embedding",
    name: "Embedding Model",
    description: "Embedding model readiness from MBZUAI (/health → checks.embedding_model.status)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.embedding_model.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "ml"],
  },
  {
    id: "mbzuai-root",
    name: "Root Endpoint",
    description: "Basic liveness check — confirms the FastAPI server is responding",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-api-root",
    name: "API Root",
    description: "API gateway check — verifies /api prefix is routable",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "API is working",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "mbzuai-auth-login",
    name: "Auth Login",
    description: "Authentication endpoint availability (POST /api/auth/login)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/auth/login`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 422,
    method: "POST",
    enabled: true,
    tags: ["production", "auth"],
  },
  {
    id: "mbzuai-auth-me",
    name: "Auth /me",
    description: "Protected user profile endpoint (expects 401 without token)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/auth/me`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "auth"],
  },
  {
    id: "mbzuai-history-stats",
    name: "Analytics Stats",
    description: "Chat history statistics endpoint auth guard (/api/history/stats). Expects 401 without token.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/history/stats`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-history-count",
    name: "Chat Count",
    description: "Total chat count endpoint auth guard (/api/history/count). Expects 401 without token.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/history/count`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-telegram-chat",
    name: "Synthetic Chat Probe",
    description: "Runs a real chat request through the MBZUAI bot to catch LLM/runtime failures that shallow health checks miss.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/telegram-chat`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 45000,
    expectedStatusCode: 200,
    jsonPath: "response",
    jsonMinLength: 40,
    jsonFailureKeywords: CHAT_PROBE_FAILURE_KEYWORDS,
    method: "POST",
    headers: CHAT_PROBE_HEADERS,
    body: JSON.stringify({
      question: "What programs does MBZUAI offer?",
      language: "English",
      previous_chats: [],
    }),
    probeTier: "llm_synthetic",
    tokenCostEstimate: 420,
    enabled: true,
    tags: ["production", "critical", "chat", "synthetic"],
  },
  {
    id: "mbzuai-metrics",
    name: "Prometheus Metrics",
    description: "Prometheus metrics export endpoint (/metrics)",
    category: "infrastructure",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/metrics`,
    checkType: "keyword",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedKeyword: "http_requests_total",
    method: "GET",
    enabled: true,
    tags: ["production", "monitoring"],
  },
  {
    id: "mbzuai-openapi",
    name: "OpenAPI Spec",
    description: "OpenAPI JSON specification availability (/openapi.json)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/openapi.json`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "mbzuai-docs",
    name: "Swagger Docs",
    description: "Interactive API documentation page (/docs)",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "mbzuai-admin-pipeline",
    name: "Pipeline Settings",
    description: "Admin RAG pipeline settings (/api/admin/pipeline-settings). Expects 401 — auth guard active.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/admin/pipeline-settings`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production", "admin"],
  },
  {
    id: "mbzuai-topics",
    name: "Topics API",
    description: "Topic management endpoint auth guard (/api/topics). Expects 401 without token.",
    category: "chatbot_backend",
    group: "mbzuai",
    url: `${MBZUAI_BASE}/api/topics`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["production"],
  },

  // ═══════════════════════════════════════════════════════════
  // MBZUAI Undergraduate Program Chatbot (DigitalOcean)
  // ═══════════════════════════════════════════════════════════

  {
    id: "mbzuai-ug-health",
    name: "Health Check",
    description: "Deep health check: validates DB, Pinecone, and embedding model",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-ug-generation-health",
    name: "Generation Health",
    description: "Direct OpenAI generation probe (/health/generation). Catches deprecated or misconfigured LLM models.",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/health/generation`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    probeTier: "llm_generation",
    tokenCostEstimate: 220,
    enabled: true,
    tags: ["production", "critical", "llm"],
  },
  {
    id: "mbzuai-ug-db",
    name: "Database Connection",
    description: "PostgreSQL connection (/health → components.database)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "components.database",
    jsonExpectedValue: "connected",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "mbzuai-ug-pinecone",
    name: "Pinecone Connection",
    description: "Pinecone vector DB connection (/health → components.pinecone)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "components.pinecone",
    jsonExpectedValue: "connected",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "vector-db"],
  },
  {
    id: "mbzuai-ug-embedding",
    name: "Embedding Model",
    description: "Embedding model initialization (/health → components.embedding_model)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "components.embedding_model",
    jsonExpectedValue: "initialized",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "ml"],
  },
  {
    id: "mbzuai-ug-root",
    name: "Root Endpoint",
    description: "Basic liveness check — confirms FastAPI server is responding",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "mbzuai-ug-api-root",
    name: "API Root",
    description: "API gateway check — verifies /api prefix is routable",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/api`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "API is working",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "mbzuai-ug-history-stats",
    name: "Analytics Stats",
    description: "Chat history statistics endpoint (/api/history/stats)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/api/history/stats`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-ug-history-count",
    name: "Chat Count",
    description: "Total chat count endpoint (/api/history/count)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/api/history/count`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "mbzuai-ug-telegram-chat",
    name: "Synthetic Chat Probe",
    description: "Runs a real chat request through the undergraduate bot to catch generation failures and broken model dependencies.",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/telegram-chat`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 45000,
    expectedStatusCode: 200,
    jsonPath: "response",
    jsonMinLength: 40,
    jsonFailureKeywords: CHAT_PROBE_FAILURE_KEYWORDS,
    method: "POST",
    headers: CHAT_PROBE_HEADERS,
    body: JSON.stringify({
      question: "What undergraduate programs are offered at MBZUAI?",
      language: "English",
      previous_chats: [],
    }),
    probeTier: "llm_synthetic",
    tokenCostEstimate: 430,
    enabled: true,
    tags: ["production", "critical", "chat", "synthetic"],
  },
  {
    id: "mbzuai-ug-openapi",
    name: "OpenAPI Spec",
    description: "OpenAPI JSON specification (/openapi.json)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/openapi.json`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "mbzuai-ug-docs",
    name: "Swagger Docs",
    description: "Interactive API documentation page (/docs)",
    category: "chatbot_backend",
    group: "mbzuai-ug",
    url: `${MBZUAI_UG_BASE}/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },

  // ═══════════════════════════════════════════════════════════
  // LAWA RAG App — UAE Government Q&A Chatbot (DigitalOcean)
  // ═══════════════════════════════════════════════════════════

  {
    id: "lawa-rag-health",
    name: "Health Check",
    description: "Liveness check for the LAWA RAG FastAPI service (/health)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "lawa-rag-generation-health",
    name: "Generation Health",
    description: "Direct OpenAI generation probe (/health/generation). Catches deprecated or misconfigured LLM models.",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/health/generation`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    probeTier: "llm_generation",
    tokenCostEstimate: 220,
    enabled: true,
    tags: ["production", "critical", "llm"],
  },
  {
    id: "lawa-rag-root",
    name: "Root Endpoint",
    description: "Basic server liveness — confirms FastAPI is up and responding",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "working",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "lawa-rag-api-root",
    name: "API Root",
    description: "API gateway routing check — verifies /api prefix is reachable",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/api`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "message",
    jsonExpectedValue: "API is working",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "lawa-rag-telegram-chat",
    name: "Synthetic Chat Probe",
    description: "Runs a real LAWA RAG question through the chatbot to catch deprecated models and other response-generation failures.",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/telegram-chat`,
    checkType: "json_query",
    checkIntervalSeconds: 300,
    timeoutMs: 45000,
    expectedStatusCode: 200,
    jsonPath: "response",
    jsonMinLength: 40,
    jsonFailureKeywords: CHAT_PROBE_FAILURE_KEYWORDS,
    method: "POST",
    headers: CHAT_PROBE_HEADERS,
    body: JSON.stringify({
      question: "How can I renew a UAE residence visa?",
      language: "English",
      response_detail_level: "short",
      previous_chats: [],
    }),
    probeTier: "llm_synthetic",
    tokenCostEstimate: 440,
    enabled: true,
    tags: ["production", "critical", "chat", "synthetic"],
  },
  {
    id: "lawa-rag-openapi",
    name: "OpenAPI Spec",
    description: "OpenAPI JSON specification availability (/openapi.json)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/openapi.json`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },
  {
    id: "lawa-rag-docs",
    name: "Swagger Docs",
    description: "Interactive Swagger API documentation page (/docs)",
    category: "chatbot_backend",
    group: "lawa-rag",
    url: `${LAWA_RAG_BASE}/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },

  // ═══════════════════════════════════════════════════════════
  // LAWA Agent Studio — AI Agent Building Platform (DO Droplet)
  // 3 services: Django Core (8000), Indexing (8080), Chatbot (8002)
  // Repo: github.com/riteshthawkar/lawa-agent-studio-unified
  // ═══════════════════════════════════════════════════════════

  // ─── Nginx Reverse Proxy ───────────────────────────────────
  {
    id: "studio-nginx",
    name: "Nginx Reverse Proxy",
    description: "Nginx gateway on port 80 — front door to the droplet",
    category: "infrastructure",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}/`,
    checkType: "http",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },

  // ─── Indexing Service (Port 8080) ──────────────────────────
  {
    id: "studio-indexing-health",
    name: "Indexing Service — Health",
    description: "FastAPI indexing service health check (:8080/health)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-root",
    name: "Indexing Service — Root",
    description: "Indexing API info endpoint (:8080/)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "running",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },
  {
    id: "studio-indexing-live",
    name: "Indexing Service — Liveness",
    description: "Contract liveness probe (:8080/health/live)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/live`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-detailed",
    name: "Indexing Service — Detailed Health",
    description: "Deep health: DB, Redis, Pinecone, Celery, Disk (:8080/health/detailed). Catches internal component failures.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-indexing-db",
    name: "Indexing Service — Database",
    description: "PostgreSQL connection from Indexing service (:8080/health/detailed → checks.database.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.database.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "studio-indexing-django",
    name: "Indexing Service — Django Backend",
    description: "Internal dependency: indexing service → Django core backend (:8080/health/detailed → checks.external_services.django_backend.status).",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.external_services.django_backend.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "backend"],
  },
  {
    id: "studio-indexing-disk",
    name: "Indexing Service — Disk Space",
    description: "Disk usage on the Agent Studio droplet (:8080/health/detailed → checks.system.status)",
    category: "infrastructure",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.system.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "infrastructure"],
  },
  {
    id: "studio-indexing-stats",
    name: "Indexing Service — Stats",
    description: "Task statistics and service uptime (:8080/stats)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/stats`,
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "analytics"],
  },
  {
    id: "studio-indexing-docs",
    name: "Indexing Service — Swagger Docs",
    description: "Interactive API docs (:8080/docs)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8080/docs`,
    checkType: "http",
    checkIntervalSeconds: 300,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    method: "GET",
    enabled: true,
    tags: ["production", "docs"],
  },

  // ─── Chatbot Widget Service (Port 8002) ────────────────────
  {
    id: "studio-chatbot-health",
    name: "Chatbot Service — Health",
    description: "FastAPI chatbot widget service health (:8002/health)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-live",
    name: "Chatbot Service — Liveness",
    description: "Contract liveness probe — confirms chatbot service process is healthy (:8002/health/live)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/live`,
    checkType: "json_query",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-detailed",
    name: "Chatbot Service — Detailed Health",
    description: "Deep health: DB, Pinecone, LAWA integration (:8002/health/detailed). Catches internal component failures.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical"],
  },
  {
    id: "studio-chatbot-db",
    name: "Chatbot Service — Database",
    description: "PostgreSQL connection from Chatbot service (:8002/health/detailed → checks.database.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 60,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.database.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "database"],
  },
  {
    id: "studio-chatbot-pinecone",
    name: "Chatbot Service — Pinecone",
    description: "Pinecone vector DB connection from Chatbot (:8002/health/detailed → checks.pinecone.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.pinecone.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "vector-db"],
  },
  {
    id: "studio-chatbot-openai",
    name: "Chatbot Service — OpenAI Model",
    description: "OpenAI/model readiness from chatbot detailed health (:8002/health/detailed → checks.openai.status).",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.openai.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production", "critical", "llm"],
  },
  {
    id: "studio-chatbot-lawa",
    name: "Chatbot Service — LAWA Integration",
    description: "LAWA platform integration health from Chatbot (:8002/health/detailed → checks.lawa_integration.status)",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8002/health/detailed`,
    checkType: "json_query",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 200,
    jsonPath: "checks.lawa_integration.status",
    jsonExpectedValue: "healthy",
    method: "GET",
    enabled: true,
    tags: ["production"],
  },

  // ─── Django Core Backend (Port 8000) ───────────────────────
  {
    id: "studio-django-health",
    name: "Django Backend — Direct Health",
    description: "Legacy direct-IP liveness check for Django core (:8000). Disabled by default in favor of internal dependency health.",
    category: "ai_agent_platform",
    group: "agent-studio",
    url: `${AGENT_STUDIO_IP}:8000/health/`,
    checkType: "http",
    checkIntervalSeconds: 30,
    timeoutMs: 10000,
    expectedStatusCode: 400, // Django rejects bare IP unless in ALLOWED_HOSTS — 400 = process is alive
    method: "GET",
    enabled: false,
    tags: ["production", "critical"],
  },

  // ═══════════════════════════════════════════════════════════
  // External APIs & LLM Providers
  // ═══════════════════════════════════════════════════════════

  {
    id: "openai-api",
    name: "OpenAI API",
    description: "OpenAI GPT API availability (used by MBZUAI + LAWA RAG for generation & reranking)",
    category: "external_api",
    group: "external",
    url: "https://api.openai.com/v1/models",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["external", "llm", "critical"],
  },
  {
    id: "anthropic-api",
    name: "Anthropic Claude API",
    description: "Anthropic Claude API availability",
    category: "external_api",
    group: "external",
    url: "https://api.anthropic.com/v1/messages",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "POST",
    enabled: true,
    tags: ["external", "llm"],
  },
  {
    id: "pinecone-api",
    name: "Pinecone API",
    description: "Pinecone vector database API (used by MBZUAI + LAWA RAG for hybrid retrieval)",
    category: "external_api",
    group: "external",
    url: "https://api.pinecone.io/",
    checkType: "http",
    checkIntervalSeconds: 120,
    timeoutMs: 15000,
    expectedStatusCode: 401,
    method: "GET",
    enabled: true,
    tags: ["external", "vector-db", "critical"],
  },
];

export function getEnabledServices(): ServiceConfig[] {
  return servicesConfig.filter((s) => s.enabled);
}

export function getServiceById(id: string): ServiceConfig | undefined {
  return servicesConfig.find((s) => s.id === id);
}

export function getServicesByCategory(category: ServiceConfig["category"]): ServiceConfig[] {
  return servicesConfig.filter((s) => s.category === category && s.enabled);
}

export function getServicesByGroup(groupId: string): ServiceConfig[] {
  return servicesConfig.filter((s) => s.group === groupId && s.enabled);
}

export const categoryLabels: Record<ServiceConfig["category"], string> = {
  chatbot_backend: "Chatbot Backends",
  ai_agent_platform: "AI Agent Platforms",
  database: "Databases",
  external_api: "External APIs & LLM Providers",
  infrastructure: "Infrastructure",
  other: "Other Services",
};

export const categoryOrder: ServiceConfig["category"][] = [
  "chatbot_backend",
  "ai_agent_platform",
  "external_api",
  "database",
  "infrastructure",
  "other",
];
